config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  root 'posts#index'

  get 'contact', to: 'pages#contact_show'
  post 'contact', to: 'pages#contact_create', as: "contact_submit"
  
  constraints ->(request) { request.env['warden'].user&.admin? } do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact_form.rb
class ContactForm
    include ActiveModel::Model
    attr_accessor :name, :email, :question
    validates :name, :email, :question, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    has_one_attached :image, service: :local

    def tiny_text
        ActionView::Base.full_sanitizer.sanitize(body).truncate 100
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # roles enum maps to a string column in the database
  enum role: { admin: "admin", user: "user"}

  def username
    return selt.email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/avo/comments_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::CommentsController < Avo::ResourcesController
end

app/controllers/avo/posts_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::PostsController < Avo::ResourcesController
end

app/controllers/avo/users_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::UsersController < Avo::ResourcesController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def contact_show
        @contact_form = ContactForm.new(
          email: current_user&.email
        )
    end
    
    def contact_create
        @contact_form = ContactForm.new(contact_params)
    
        if @contact_form.valid?
            ContactMailer.contact_email(@contact_form).deliver_now
            redirect_to contact_path, notice: "Your message was sent successfully."
        else
            redirect_to contact_path, alert: "Please fill in all required fields."
        end
    end
    
    private
    
    def contact_params
        params.require(:contact_form).permit(:name, :email, :question)
    end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
  @posts = Post.all.order(created_at: :desc)
  @pagy, @posts_show = pagy Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-lg" aria-label="Offcanvas navbar large">
    <div class="container-fluid d-flex justify-content-between">
      <a class="navbar-brand col-6 col-lg-2" href="/">
        <%= image_tag "Logo.png", class: 'col-8 col-lg-12'%>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2" aria-controls="offcanvasNavbar2">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar2" aria-labelledby="offcanvasNavbar2Label">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbar2Label">Offcanvas</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body flex-lg-row justify-content-between">
          <div class="d-flex col-lg-8 flex-grow-1">
            <ul class="navbar-nav mx-auto">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">POČETNA</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">USLUGE</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="#">PROFIL</a>
                <!-- <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul> -->
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/posts">BLOG</a>
              </li>
            </ul>
          </div>
          
          <% if current_user %>
          <div class="d-flex mt-3 mt-lg-0 float-lg-end col-lg-2">
            <strong><%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'text-black btn-text btn' %></strong>
          </div>
          <% else %>
          <div class="d-flex mt-3 mt-lg-0 float-lg-end">
            <button class="btn"><i class="fa-solid fa-user-plus"></i><strong> <%= link_to 'Sing up', new_user_registration_path, class: 'text-black btn-text' %></strong></button>
            <button class="btn" style="margin-left:15px;"><i class="fa-solid fa-arrow-right-to-bracket"></i><strong> <%= link_to 'Sign in', new_user_session_path, class: 'text-black btn-text' %></strong></button>
            <!-- <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button> -->
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakeupBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-kWJs9RJLVoyeeAV9KsKzS6n1FF/Y/9jFFVx7sPb4yT0EBjAx0ODCh2gKjCq32BtM8Zrsk3t7D2eG9OKwihv75Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  
  
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  
  <body>
    <div class="wrapper d-flex flex-column min-vh-100">
      <nav class="fixed left-1/2 transform -translate-x-1/2 t-0 px-2 lg:px-5 py-2 nav-color">
        <%= render partial: 'layouts/navbar' %>
      </nav>
  
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <div class="d-flex flex-column my-auto">
        <%= yield %>
      </div>
      <footer class="footer">
        <div class="flex flex-col mt-4 mb-5 bg-white py-5">
          <div class="container flex footer-logo flex-grow-1 m-auto text-center my-3">
            <%= image_tag "Logo.png"%>
          </div>
          <div class="container d-flex justify-content-center gap-4 mt-5 gap-lg-5 m-auto text-center my-3">
            <a href="#">
              <i class="fa-brands fa-facebook"></i>
            </a>
            <a href="#">
              <i class="fa-brands fa-twitter"></i>
            </a>
            <a href="#">
              <i class="fa-brands fa-instagram"></i>
            </a>
            <a href="#">
              <i class="fa-brands fa-youtube"></i>
            </a>
            <a href="/contact">
              <i class="fa-solid fa-envelope"></i>
            </a>
          </div> 
        </div>
        <div class="px-2 lg:px-5 py-2 footer-bottom">
          <p class="mb-0">
            Copyright <span>&copy</span> 2023 All Rights Reserved
          </p>
        </div>
        
      </footer>
    </div>
  </body>
   

  
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
</html>

app/views/pages/contact_show.html.erb
<div class="lg:flex flex-col my-5">
  <div class="col-6 col-lg-2 mx-auto text-center">
    <%= image_tag "Logo.png", class: 'col-8 m-auto col-lg-12' %>
  </div>

  <div class="col-11 col-md-8 col-lg-6 m-auto mt-4">
    <%= form_for @contact_form, url:contact_path do |f| %>
    
    <div class="form-group my-2">
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control rounded-0 border-1 border-dark', placeholder: 'Korisničko ime' %>
    </div>
    
    <% unless current_user %>
    <div class="field-group my-2">
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control rounded-0 border-1 border-dark', placeholder: 'Email' %>
    </div>
    <% end %>

    <div class="field-group my-4">
      <%= f.text_area :question, autofocus: true, autocomplete: "question", class: 'form-control rounded-0 border-1 h-100 border-dark', rows: 6, placeholder: 'Unesi poruku' %>
    </div>
    <div class="mb-4">
        <%= f.submit "Pošalji", width: '100%' %>
    </div>
    <% end %>
  </div>
</div>  

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">

<%= image_tag post.image, height: '100' , width: '100'%>
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<!-- <% if current_user %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }%>
<% end %> -->

<!-- <div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div> -->

<div class="container flex-column gap-3 justify-content-between flex-lg-row d-flex my-5">
  <div class="col-12 col-lg-5 col-xl-5">
    <div> 
      <h3><strong><%= @posts[0].title %></strong></h3>
    </div>
    <div class="my-4">
      <%= @posts[0].body.truncate(250, omission: '...') %>
    </div>
    <button type="button" class="btn"><%= link_to "Pročitaj više", @posts.first, class: 'text-black btn-text' %></button> 
  </div> 
  <div class="col-12 col-lg-6 col-xl-5">
    <%= image_tag @posts[0].image, class: 'photo', width: '100%'%>
  </div> 
</div>

<div class="purple py-4">
  <div class="container">
    <div class="post-slide">
      <% @posts.each do |post| %>
      <article class="card text-left p-0">  
        <%= image_tag post.image, class: 'photo', height: '100%', width: '100%', position: 'absolute' %>
        <div class="post-date p-2 btn">
          <%= post.created_at.strftime("%d/%m/%Y") %>
        </div>
        <div class="card-body">
          <h5 class="card-title mb-2"><%= post.title %></h5>
          <p class="card-text my-4"><%= post.body.truncate(180, omission: '...') %></p>
          <button type="button" class="btn my-2"><%= link_to "Pročitaj više", post, class: 'text-black btn-text' %></button>
        </div>
      </article>
      <% end %>
    </div>
      <%== pagy_nav(@pagy) %>
  </div>
</div>



<!-- <%= link_to "New post", new_post_path %> -->

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>